version: '3.8'
 
services:
  # nginx:
  #   container_name: core_web
  #   restart: on-failure
  #   image: nginx:stable
  #   volumes:
  #     - nginx_secrets:/etc/letsencrypt
  #     - ./nginx/user_conf.d:/etc/nginx/user_conf.d
  #   ports:
  #     - "80:80"
  #     - "443:443"

  #   depends_on:
  #     - web
  web:
   container_name: core_shareclub
   build: .
   restart: always
   env_file: ./ShareClub/.env
  #  command: >
  #     sh -c "gunicorn ShareClub.wsgi:application --bind 0.0.0.0:8000"
   volumes:
     - .:/ShareClub
     - static_volume:/ShareClub/static
   depends_on:
     - db   
   ports:
     - 80:8000

  db:
    container_name: core_db
    image: postgres:14.1-alpine
    env_file:  ./ShareClub/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
     - 5433:5432
  

volumes:
  static_volume:
  postgres_data:
  nginx_secrets: