# Generated by Django 2.2.24 on 2021-11-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyClub', '0002_auto_20211129_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='service',
            new_name='reviewOffer',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='creater',
            new_name='reviewOwner',
        ),
    ]
