# Generated by Django 2.2.24 on 2021-12-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclub', '0003_offer_is_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userReservehour',
            field=models.IntegerField(default=0),
        ),
    ]
