# Generated by Django 2.2.24 on 2021-11-29 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyClub', '0003_auto_20211129_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offerTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
