# Generated by Django 2.2.24 on 2021-11-29 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyClub', '0004_auto_20211129_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
