# Generated by Django 2.2.24 on 2021-11-30 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyClub', '0005_auto_20211129_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventDuration',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='offer',
            name='offerDuration',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
