# Generated by Django 2.2.24 on 2021-11-30 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyClub', '0006_auto_20211130_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userFollowers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='userPicture',
            field=models.ImageField(blank=True, default='uploads/profile_pictures/default.png', upload_to='uploads/profile_pictures/'),
        ),
    ]
