# Generated by Django 2.2.24 on 2021-12-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclub', '0006_userprofile_usersurname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userCredibility',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='offerapplication',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
