# Generated by Django 2.2.24 on 2021-11-30 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyClub', '0007_auto_20211130_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userFollowers',
            field=models.ManyToManyField(blank=True, related_name='userfollowers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OfferApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved', models.BooleanField(default=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyClub.Offer')),
            ],
        ),
    ]
