# Generated by Django 2.2.24 on 2021-12-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclub', '0008_auto_20211219_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerPicture',
            field=models.ImageField(blank=True, default='uploads/event_pictures/default.png', upload_to='uploads/offer_pictures/'),
        ),
    ]
