# Generated by Django 2.2.24 on 2021-12-03 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyClub', '0008_auto_20211130_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerapplication',
            old_name='date',
            new_name='applicationDate',
        ),
        migrations.RenameField(
            model_name='offerapplication',
            old_name='service',
            new_name='appliedService',
        ),
        migrations.RenameField(
            model_name='offerapplication',
            old_name='approved',
            new_name='isApproved',
        ),
    ]
