# Generated by Django 2.2.24 on 2021-12-03 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyClub', '0009_auto_20211203_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerapplication',
            old_name='appliedService',
            new_name='appliedOffer',
        ),
    ]
