# Generated by Django 2.2.24 on 2021-12-26 12:31

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('myclub', '0012_auto_20211224_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offerMap',
            field=location_field.models.plain.PlainLocationField(default='41.0255493,28.9742571', max_length=63),
        ),
    ]
