# Generated by Django 2.2.24 on 2021-12-26 13:11

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('myclub', '0014_auto_20211226_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventMap',
            field=location_field.models.plain.PlainLocationField(default='41.031964, 29.008841', max_length=63),
        ),
    ]
