# Generated by Django 2.2.24 on 2021-12-31 01:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myclub', '0016_userratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerCapacity',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='EventApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('isApproved', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('appliedEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclub.Event')),
            ],
        ),
    ]
