# Generated by Django 2.2.24 on 2022-01-01 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclub', '0019_auto_20220101_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventCapacity',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
