# Generated by Django 2.2.24 on 2022-01-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclub', '0021_auto_20220101_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventDescription',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventName',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerDescription',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerName',
            field=models.TextField(max_length=100),
        ),
    ]
