# Generated by Django 2.2.24 on 2022-01-02 12:09

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myclub', '0022_auto_20220101_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventCategory',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerCategory',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerDate',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(datetime.date(2022, 1, 2))]),
        ),
    ]
