# Generated by Django 2.2.24 on 2022-01-11 21:36

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myclub', '0024_userratings_ratingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offerTag',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerDate',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(datetime.date(2022, 1, 11))]),
        ),
    ]
